# -*- coding: utf-8 -*-
"""graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HXFAg1IbU1DLlCXpWm5GUqFIRNPAwcR
"""

import matplotlib.pyplot as plt
import seaborn as sns

countries = [
     "Indonesia", "Pakistan", "Bangladesh",
    "Japan", "Philippines", "Vietnam", "Turkey", "Iran"
]
populations = [277, 240, 169, 124, 117, 99, 86, 85]  # Population in millions
gdp_per_capita = [4600, 1700, 2500, 39000, 3800, 4100, 10500, 6200]  # GDP per capita (USD)

bubble_size = []
for p in populations:
    bubble_size.append(p * 5)
plt.figure(figsize=(10, 6))
sns.scatterplot(x=gdp_per_capita, y=populations, size=bubble_size, sizes=(100, 3000), hue=countries, palette="tab10", edgecolor="black", alpha=0.7)

plt.xlabel("Нэг хүнд ногдох ДНБ(доллараар)")
plt.ylabel("Хүн ам (саяар)")
plt.title("Азийн 8 улсын хүн ам болон НХНДНБ ")
plt.legend(title="Улсууд", loc='center left', bbox_to_anchor=(1, 0.5))

plt.show()

import numpy as np
import matplotlib.pyplot as plt

fruits = ['Алим', 'Банана', 'Жүрж', 'Усан үзэм']
nutrients = ['Нүүрс ус', 'Уураг', 'Өөх тос']

data = {
    'Алим': [25, 0.5, 0.3],
    'Банана': [27, 1.3, 0.4],
    'Жүрж': [12, 1.2, 0.2],
    'Усан үзэм': [18, 0.7, 0.2]
}

df = pd.DataFrame(data, index=nutrients)
df = df.T

df.plot(kind='bar', figsize=(10, 6), width=0.7)
plt.title('Жимснүүдийн шим тэжээлийн харьцаа')
plt.xlabel('Жимс')
plt.ylabel('100граммд эзлэх хэмжээ')
plt.legend(title='Шим тэжээл')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
print(df)

import matplotlib.pyplot as plt

languages = ['English', 'Mandarin Chinese', 'Hindi', 'Spanish', 'French', 'Arabic', 'Bengali', 'Portuguese', 'Russian']
speakers = [1500, 1100, 600, 560, 310, 274, 273, 265, 258]

#autotext heseg n huwiar ilerhiilehiig uzuulne
plt.figure(figsize=(8, 8))
wedges, texts, autotexts = plt.pie(speakers, labels=languages, autopct='%1.1f%%', pctdistance=0.85)

#goliin tsagaaniig uusgeh
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
plt.gca().add_artist(centre_circle)

plt.title("Most Spoken Languages in the World")

plt.show()

import yfinance as yf
import matplotlib.pyplot as plt

aapl = yf.Ticker("AAPL")
data = aapl.history(period="1y")

data['Return'] = data['Close'].pct_change()
data = data.dropna()
plt.figure(figsize=(10, 6))
plt.plot(data['Return'])
plt.title('AAPL Daily Returns - Last 1 Year')
plt.xlabel('Date')
plt.ylabel('Daily Return')

# Show the plot
plt.show()